[package]
name = "chess_escrow"
version = "1.0.0"
authors = ["Chess Game Developer"]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }

[addresses]
chess_escrow = "_" 